//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDAparser.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICasemanagerReceiver")]
    public interface ICasemanagerReceiver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasemanagerReceiver/receiveEducationEvaluation", ReplyAction="http://tempuri.org/ICasemanagerReceiver/receiveEducationEvaluationResponse")]
        bool receiveEducationEvaluation(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICasemanagerReceiverChannel : ServiceReference1.ICasemanagerReceiver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CasemanagerReceiverClient : System.ServiceModel.ClientBase<ServiceReference1.ICasemanagerReceiver>, ServiceReference1.ICasemanagerReceiver {
        
        public CasemanagerReceiverClient() {
        }
        
        public CasemanagerReceiverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CasemanagerReceiverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasemanagerReceiverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasemanagerReceiverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool receiveEducationEvaluation(string data) {
            return base.Channel.receiveEducationEvaluation(data);
        }
    }
}
