//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDAparser.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICasemanagerReceiver")]
    public interface ICasemanagerReceiver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasemanagerReceiver/receiveEducationEvaluation", ReplyAction="http://tempuri.org/ICasemanagerReceiver/receiveEducationEvaluationResponse")]
        bool receiveEducationEvaluation(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasemanagerReceiver/receiveProfile", ReplyAction="http://tempuri.org/ICasemanagerReceiver/receiveProfileResponse")]
        bool receiveProfile(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasemanagerReceiver/receiveEducationPlannings", ReplyAction="http://tempuri.org/ICasemanagerReceiver/receiveEducationPlanningsResponse")]
        bool receiveEducationPlannings(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasemanagerReceiver/receiveProfileMilk", ReplyAction="http://tempuri.org/ICasemanagerReceiver/receiveProfileMilkResponse")]
        bool receiveProfileMilk(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasemanagerReceiver/receiveServiceProvisionEducation", ReplyAction="http://tempuri.org/ICasemanagerReceiver/receiveServiceProvisionEducationResponse")]
        bool receiveServiceProvisionEducation(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasemanagerReceiver/getCasemanagerProfile", ReplyAction="http://tempuri.org/ICasemanagerReceiver/getCasemanagerProfileResponse")]
        string getCasemanagerProfile(string cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasemanagerReceiver/getCasemanagerQuestionare", ReplyAction="http://tempuri.org/ICasemanagerReceiver/getCasemanagerQuestionareResponse")]
        string getCasemanagerQuestionare(string cid, string planNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasemanagerReceiver/getCasemanagerPlanning", ReplyAction="http://tempuri.org/ICasemanagerReceiver/getCasemanagerPlanningResponse")]
        string getCasemanagerPlanning(string cid, string planNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasemanagerReceiver/getProfileList", ReplyAction="http://tempuri.org/ICasemanagerReceiver/getProfileListResponse")]
        string[] getProfileList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICasemanagerReceiverChannel : ServiceReference1.ICasemanagerReceiver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CasemanagerReceiverClient : System.ServiceModel.ClientBase<ServiceReference1.ICasemanagerReceiver>, ServiceReference1.ICasemanagerReceiver {
        
        public CasemanagerReceiverClient() {
        }
        
        public CasemanagerReceiverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CasemanagerReceiverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasemanagerReceiverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasemanagerReceiverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool receiveEducationEvaluation(string data) {
            return base.Channel.receiveEducationEvaluation(data);
        }
        
        public bool receiveProfile(string data) {
            return base.Channel.receiveProfile(data);
        }
        
        public bool receiveEducationPlannings(string data) {
            return base.Channel.receiveEducationPlannings(data);
        }
        
        public bool receiveProfileMilk(string data) {
            return base.Channel.receiveProfileMilk(data);
        }
        
        public bool receiveServiceProvisionEducation(string data) {
            return base.Channel.receiveServiceProvisionEducation(data);
        }
        
        public string getCasemanagerProfile(string cid) {
            return base.Channel.getCasemanagerProfile(cid);
        }
        
        public string getCasemanagerQuestionare(string cid, string planNo) {
            return base.Channel.getCasemanagerQuestionare(cid, planNo);
        }
        
        public string getCasemanagerPlanning(string cid, string planNo) {
            return base.Channel.getCasemanagerPlanning(cid, planNo);
        }
        
        public string[] getProfileList() {
            return base.Channel.getProfileList();
        }
    }
}
